### PR TITLE
+ add: "Solve nearest conflict" command moves caret to start of confl…

### LINKED ISSUE #9: set caret to start of current conflict
@Alexey-T

we can add new features:
1. set caret to start of current conflict when using command: `Solve nearest conflict`
    caret must be moved because it's quite logical: i can move around the conflict and analyze.
2. make dialog menu narrower and move it to the right of the screen (not supported by API? we have only `DMENU_CENTERED`).
    menu dialog is quite big (especially with high DPI) and it covers the conflict, user can't see anything!

what options do we have to move dialog menu out of center?
maybe use something else? not dlg_menu?

...
thinking about using "validate" panel.
but when i press Enter inside validate panel, this event is not fired:
_* on_output_nav(self, ed_self, text, tag): Called on **clicking** line, or pressing **Enter**, in the Output or **Validate** panel. Param "text" is clicked line, param "tag" is int value associated with line._

and clicking on line in validate panel is also not working, only double-clicking works. (but i can apparently use 
PROC_GET_VALIDATE_FORM+on_key_down)

...
maybe it's better not to change old command, but create new command that will use validate panel to quickly solve all conflicts one by one using "1", "2", "3" keys, for example.

### PR DESCRIPTION
**Pull request by veksha**
…ict.

- fix: made width and height of dialog menu smaller so it will not cover editor so much.

resolves https://github.com/halfbrained/cuda_git_conflict/issues/9

### CODE REVIEW

**Comment by Alexey-T** [comment]
about 'w'. dlg_menu covers part of the editor, it's the problem? then we need movable window. ie not dlg_menu . so - need the new dialog. only if you have time to make it! I am ok with the current code.

**Comment by veksha** [comment]
ok. lets apply this for now ?

don't have idea how new dialog should look like. custom listbox?

**Comment by CudaText-addons** [comment]
only idea: dialog with a listbox_ex (or maybe simple listbox) on the top, and OK/Cancel buttons on the bottom on the panel.

**Comment by veksha** [comment]
and make it non-modal? , also after solving one conflict automatically solve next?

(+remember win pos in config)

**Comment by CudaText-addons** [comment]
non-modal is OK. then OK/Cancel are not needed, only Close or w/o buttons.

>remember win pos in config

yes.
But! I do not have conflicts usually (very very rare, and I want to solve it by hands)


>after solving one conflict automatically solve next?

not needed for me.

**Comment by veksha** [comment]
> non-modal is OK. then OK/Cancel are not needed, only Close or w/o buttons.

if no buttons - how to resolve conflict? button "Solve"?

> But! I do not have conflicts usually (very very rare, and I want to solve it by hands

by hands means without plugin at all?
if user is using this plugin he wants to at least jump to conflict using command "solve", then maybe solve it by hands there, then jump to next using command "solve.." and maybe automatically solve by choosing "current/incoming/both".

**Comment by CudaText-addons** [comment]
>how to resolve conflict? button "Solve"?

ah, right.

>by hands means without plugin at all?

yes, i did it so. last my conflict was X yrs ago maybe. plugin not existed.

**Pull request merged**
